### ISSUE TITLE
IP address not found

### ISSUE THREAD

**Issue by bonninjd** [judge2005/BambuLights#2]
Hi, Great project.  Thank you for your work.
I programed the board, was able to connect directly and enter the wifi info, but when I enter http://bambulights.local/ in my browser, it says page can't be found.  I know my browser can handle .local addresses, as I have other projects that do this.  Any ideas?

**Comment by judge2005** [comment]
Did you load the files system to the board too?On Jun 24, 2024, at 12:03 PM, bonninjd ***@***.***> wrote:﻿
Hi, Great project.  Thank you for your work.
I programed the board, was able to connect directly and enter the wifi info, but when I enter http://bambulights.local/ in my browser, it says page can't be found.  I know my browser can handle .local addresses, as I have other projects that do this.  Any ideas?

**Comment by bonninjd** [comment]
That worked!  I used a ESP-WROOM-32 board and was trying to build a version for that.
As a future improvement, maybe adding rainbow effects and chasing as an option.
Thank you again!

**Comment by judge2005** [comment]
> That worked! I used a ESP-WROOM-32 board and was trying to build a version for that. As a future improvement, maybe adding rainbow effects and chasing as an option. Thank you again!

I would like to add more effects. If you have some examples, and when they might be used, that would be useful. I think there are two general cases:

1. As a transition between states (currently a cross-fade is hard-coded). I could see a color-wipe being nice too for example.
2. As a state indication (currently just steady and pulsing).

I found this link on reddit: https://www.tweaking4all.com/hardware/arduino/adruino-led-strip-effects/
